const solver = require('./day-07');

// Code for single example
const EXAMPLE = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

test('Day 7', () => {
  expect(solver(EXAMPLE)).toEqual([ 21, 40 ]);
});

// Code for multiple examples
/*
const EXAMPLES = [
  { input: '', output: [ undefined, undefined ] },
];

EXAMPLES.forEach(({ input, output }, i) => {
  test(`Day 7, example ${i}`, () => {
    expect(solver(input)).toEqual(output);
  });
});
*/
