const solver = require('./day-06');

const EXAMPLE = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;

test('Day 6', () => {
  expect(solver(EXAMPLE)).toEqual([ 41, 6 ]);
});
